# Generated by Django 3.2.25 on 2024-05-23 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_remove_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.FloatField(serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, serialize=False),
        ),
    ]
