version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django
    command: gunicorn event_management.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/static/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
